
package controllerpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControllerInterface", targetNamespace = "http://controllerPackage/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControllerInterface {


    /**
     * 
     * @param registrationRoleOfUser
     * @param registrationId
     */
    @WebMethod
    @Action(input = "http://controllerPackage/ControllerInterface/registrationRequest", output = "http://controllerPackage/ControllerInterface/registrationResponse")
    public void registration(
        @WebParam(name = "registrationRoleOfUser", partName = "registrationRoleOfUser")
        Role registrationRoleOfUser,
        @WebParam(name = "registrationId", partName = "registrationId")
        int registrationId);

    /**
     * 
     * @param staffID
     * @param studentID
     */
    @WebMethod
    @Action(input = "http://controllerPackage/ControllerInterface/enrollRequest", output = "http://controllerPackage/ControllerInterface/enrollResponse")
    public void enroll(
        @WebParam(name = "staffID", partName = "staffID")
        int staffID,
        @WebParam(name = "studentID", partName = "studentID")
        int studentID);

}
