
package controllerpackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControllerImplService", targetNamespace = "http://controllerPackage/", wsdlLocation = "http://localhost:8080/controllerService/?wsdl")
public class ControllerImplService
    extends Service
{

    private final static URL CONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName CONTROLLERIMPLSERVICE_QNAME = new QName("http://controllerPackage/", "ControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/controllerService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        CONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public ControllerImplService() {
        super(__getWsdlLocation(), CONTROLLERIMPLSERVICE_QNAME);
    }

    public ControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLERIMPLSERVICE_QNAME, features);
    }

    public ControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLERIMPLSERVICE_QNAME);
    }

    public ControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLERIMPLSERVICE_QNAME, features);
    }

    public ControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerInterface
     */
    @WebEndpoint(name = "ControllerImplPort")
    public ControllerInterface getControllerImplPort() {
        return super.getPort(new QName("http://controllerPackage/", "ControllerImplPort"), ControllerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerInterface
     */
    @WebEndpoint(name = "ControllerImplPort")
    public ControllerInterface getControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllerPackage/", "ControllerImplPort"), ControllerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw CONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return CONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
