
package controllerpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControllerInterface", targetNamespace = "http://controllerPackage/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    staffservice.ObjectFactory.class,
    studentservice.ObjectFactory.class,
    controllerpackage.ObjectFactory.class
})
public interface ControllerInterface {


    /**
     * 
     * @param registrationRoleOfUser
     * @param registrationId
     */
    @WebMethod
    @Action(input = "http://controllerPackage/ControllerInterface/registrationRequest", output = "http://controllerPackage/ControllerInterface/registrationResponse")
    public void registration(
        @WebParam(name = "registrationRoleOfUser", partName = "registrationRoleOfUser")
        Role registrationRoleOfUser,
        @WebParam(name = "registrationId", partName = "registrationId")
        int registrationId);

    /**
     * 
     * @param assignYear
     * @param assignMc
     * @param assignStaffID
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "assignResult", partName = "assignResult")
    @Action(input = "http://controllerPackage/ControllerInterface/assignRequest", output = "http://controllerPackage/ControllerInterface/assignResponse")
    public int assign(
        @WebParam(name = "assignStaffID", partName = "assignStaffID")
        int assignStaffID,
        @WebParam(name = "assignMc", partName = "assignMc")
        staffservice.ModuleCode assignMc,
        @WebParam(name = "assignYear", partName = "assignYear")
        String assignYear);

    /**
     * 
     * @param insertMarkStudID
     * @param insertMarkStaffID
     * @param insertedMark
     * @param insertMarkMC
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "insertMarkResult", partName = "insertMarkResult")
    @Action(input = "http://controllerPackage/ControllerInterface/insertMarkRequest", output = "http://controllerPackage/ControllerInterface/insertMarkResponse")
    public int insertMark(
        @WebParam(name = "insertMarkStaffID", partName = "insertMarkStaffID")
        int insertMarkStaffID,
        @WebParam(name = "insertMarkMC", partName = "insertMarkMC")
        studentservice.ModuleCode insertMarkMC,
        @WebParam(name = "insertedMark", partName = "insertedMark")
        double insertedMark,
        @WebParam(name = "insertMarkStudID", partName = "insertMarkStudID")
        int insertMarkStudID);

    /**
     * 
     * @param printMarkStudID
     * @param printMarkStaffID
     * @param printMarkMC
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "printMarkResult", partName = "printMarkResult")
    @Action(input = "http://controllerPackage/ControllerInterface/printMarkRequest", output = "http://controllerPackage/ControllerInterface/printMarkResponse")
    public String printMark(
        @WebParam(name = "printMarkStaffID", partName = "printMarkStaffID")
        int printMarkStaffID,
        @WebParam(name = "printMarkMC", partName = "printMarkMC")
        studentservice.ModuleCode printMarkMC,
        @WebParam(name = "printMarkStudID", partName = "printMarkStudID")
        int printMarkStudID);

    /**
     * 
     * @param enrollYear
     * @param enrollStaffID
     * @param enrollStudID
     * @param enrollMC
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "enrollResult", partName = "enrollResult")
    @Action(input = "http://controllerPackage/ControllerInterface/enrollRequest", output = "http://controllerPackage/ControllerInterface/enrollResponse")
    public int enroll(
        @WebParam(name = "enrollStaffID", partName = "enrollStaffID")
        int enrollStaffID,
        @WebParam(name = "enrollMC", partName = "enrollMC")
        studentservice.ModuleCode enrollMC,
        @WebParam(name = "enrollYear", partName = "enrollYear")
        String enrollYear,
        @WebParam(name = "enrollStudID", partName = "enrollStudID")
        int enrollStudID);

}
