
package staffpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffsInterface", targetNamespace = "http://staffPackage/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffsInterface {


    /**
     * 
     * @param assignModuleYear
     * @param assignModuleStaffID
     * @param assignModuleMc
     * @return
     *     returns int
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "assignModuleResult", partName = "assignModuleResult")
    @Action(input = "http://staffPackage/StaffsInterface/assignModuleRequest", output = "http://staffPackage/StaffsInterface/assignModuleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://staffPackage/StaffsInterface/assignModule/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://staffPackage/StaffsInterface/assignModule/Fault/IOException")
    })
    public int assignModule(
        @WebParam(name = "assignModuleStaffID", partName = "assignModuleStaffID")
        int assignModuleStaffID,
        @WebParam(name = "assignModuleMc", partName = "assignModuleMc")
        ModuleCode assignModuleMc,
        @WebParam(name = "assignModuleYear", partName = "assignModuleYear")
        String assignModuleYear)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param staffID
     * @return
     *     returns boolean
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "staffExistResult", partName = "staffExistResult")
    @Action(input = "http://staffPackage/StaffsInterface/staffExistRequest", output = "http://staffPackage/StaffsInterface/staffExistResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://staffPackage/StaffsInterface/staffExist/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://staffPackage/StaffsInterface/staffExist/Fault/IOException")
    })
    public boolean staffExist(
        @WebParam(name = "StaffID", partName = "StaffID")
        int staffID)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addStaffId
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @Action(input = "http://staffPackage/StaffsInterface/addStaffRequest", output = "http://staffPackage/StaffsInterface/addStaffResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://staffPackage/StaffsInterface/addStaff/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://staffPackage/StaffsInterface/addStaff/Fault/IOException")
    })
    public void addStaff(
        @WebParam(name = "addStaffId", partName = "addStaffId")
        int addStaffId)
        throws IOException_Exception, JAXBException_Exception
    ;

}
