
package controllerpackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControllerService", targetNamespace = "http://controllerPackage/", wsdlLocation = "http://localhost:8080/controllerService/?wsdl")
public class ControllerService
    extends Service
{

    private final static URL CONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLLERSERVICE_EXCEPTION;
    private final static QName CONTROLLERSERVICE_QNAME = new QName("http://controllerPackage/", "ControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/controllerService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLERSERVICE_WSDL_LOCATION = url;
        CONTROLLERSERVICE_EXCEPTION = e;
    }

    public ControllerService() {
        super(__getWsdlLocation(), CONTROLLERSERVICE_QNAME);
    }

    public ControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLERSERVICE_QNAME, features);
    }

    public ControllerService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLERSERVICE_QNAME);
    }

    public ControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLERSERVICE_QNAME, features);
    }

    public ControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerInterface
     */
    @WebEndpoint(name = "ControllerPort")
    public ControllerInterface getControllerPort() {
        return super.getPort(new QName("http://controllerPackage/", "ControllerPort"), ControllerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerInterface
     */
    @WebEndpoint(name = "ControllerPort")
    public ControllerInterface getControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllerPackage/", "ControllerPort"), ControllerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLERSERVICE_EXCEPTION!= null) {
            throw CONTROLLERSERVICE_EXCEPTION;
        }
        return CONTROLLERSERVICE_WSDL_LOCATION;
    }

}
