
package controllerpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControllerInterface", targetNamespace = "http://controllerPackage/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControllerInterface {


    /**
     * 
     * @param loginCheckPassword
     * @param loginCheckUsername
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "loginCheckResult", partName = "loginCheckResult")
    @Action(input = "http://controllerPackage/ControllerInterface/loginCheckRequest", output = "http://controllerPackage/ControllerInterface/loginCheckResponse")
    public boolean loginCheck(
        @WebParam(name = "loginCheckUsername", partName = "loginCheckUsername")
        String loginCheckUsername,
        @WebParam(name = "loginCheckPassword", partName = "loginCheckPassword")
        String loginCheckPassword);

    /**
     * 
     * @param registrationRoleOfUser
     * @param registrationId
     */
    @WebMethod
    @Action(input = "http://controllerPackage/ControllerInterface/registrationRequest", output = "http://controllerPackage/ControllerInterface/registrationResponse")
    public void registration(
        @WebParam(name = "registrationRoleOfUser", partName = "registrationRoleOfUser")
        Role registrationRoleOfUser,
        @WebParam(name = "registrationId", partName = "registrationId")
        int registrationId);

}
