
package studentpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsInterface", targetNamespace = "http://studentPackage/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsInterface {


    /**
     * 
     * @param addModuleMc
     * @param addModuleId
     * @param addModuleYear
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "addModuleResult", partName = "addModuleResult")
    @Action(input = "http://studentPackage/StudentsInterface/addModuleRequest", output = "http://studentPackage/StudentsInterface/addModuleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentPackage/StudentsInterface/addModule/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentPackage/StudentsInterface/addModule/Fault/IOException")
    })
    public int addModule(
        @WebParam(name = "addModuleId", partName = "addModuleId")
        int addModuleId,
        @WebParam(name = "addModuleMc", partName = "addModuleMc")
        ModuleCode addModuleMc,
        @WebParam(name = "addModuleYear", partName = "addModuleYear")
        String addModuleYear)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addStudentId
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://studentPackage/StudentsInterface/addStudentRequest", output = "http://studentPackage/StudentsInterface/addStudentResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentPackage/StudentsInterface/addStudent/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentPackage/StudentsInterface/addStudent/Fault/IOException")
    })
    public void addStudent(
        @WebParam(name = "addStudentId", partName = "addStudentId")
        int addStudentId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param mc
     * @param insertMarkId
     * @param mark
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "insertMarkResult", partName = "insertMarkResult")
    @Action(input = "http://studentPackage/StudentsInterface/insertMarkRequest", output = "http://studentPackage/StudentsInterface/insertMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentPackage/StudentsInterface/insertMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentPackage/StudentsInterface/insertMark/Fault/IOException")
    })
    public int insertMark(
        @WebParam(name = "insertMarkId", partName = "insertMarkId")
        int insertMarkId,
        @WebParam(name = "mc", partName = "mc")
        ModuleCode mc,
        @WebParam(name = "mark", partName = "mark")
        double mark)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param printMarkId
     * @param printMarkMc
     * @return
     *     returns java.lang.String
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "printMarkResult", partName = "printMarkResult")
    @Action(input = "http://studentPackage/StudentsInterface/printMarkRequest", output = "http://studentPackage/StudentsInterface/printMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentPackage/StudentsInterface/printMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentPackage/StudentsInterface/printMark/Fault/IOException")
    })
    public String printMark(
        @WebParam(name = "printMarkId", partName = "printMarkId")
        int printMarkId,
        @WebParam(name = "printMarkMc", partName = "printMarkMc")
        ModuleCode printMarkMc)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getStudentId
     * @return
     *     returns boolean
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "getStudentResult", partName = "getStudentResult")
    @Action(input = "http://studentPackage/StudentsInterface/studentExistsRequest", output = "http://studentPackage/StudentsInterface/studentExistsResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentPackage/StudentsInterface/studentExists/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentPackage/StudentsInterface/studentExists/Fault/IOException")
    })
    public boolean studentExists(
        @WebParam(name = "getStudentId", partName = "getStudentId")
        int getStudentId)
        throws IOException_Exception, JAXBException_Exception
    ;

}
