
package studentservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentsImplService", targetNamespace = "http://studentService/", wsdlLocation = "http://localhost:8080/studentService/?wsdl")
public class StudentsImplService
    extends Service
{

    private final static URL STUDENTSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTSIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTSIMPLSERVICE_QNAME = new QName("http://studentService/", "StudentsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/studentService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTSIMPLSERVICE_EXCEPTION = e;
    }

    public StudentsImplService() {
        super(__getWsdlLocation(), STUDENTSIMPLSERVICE_QNAME);
    }

    public StudentsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSIMPLSERVICE_QNAME, features);
    }

    public StudentsImplService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSIMPLSERVICE_QNAME);
    }

    public StudentsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSIMPLSERVICE_QNAME, features);
    }

    public StudentsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentsInterface
     */
    @WebEndpoint(name = "StudentsImplPort")
    public StudentsInterface getStudentsImplPort() {
        return super.getPort(new QName("http://studentService/", "StudentsImplPort"), StudentsInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentsInterface
     */
    @WebEndpoint(name = "StudentsImplPort")
    public StudentsInterface getStudentsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://studentService/", "StudentsImplPort"), StudentsInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTSIMPLSERVICE_EXCEPTION;
        }
        return STUDENTSIMPLSERVICE_WSDL_LOCATION;
    }

}
