
package studentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsInterface", targetNamespace = "http://studentService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsInterface {


    /**
     * 
     * @param loginCheckPassword
     * @param loginCheckUsername
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "loginCheckResult", partName = "loginCheckResult")
    @Action(input = "http://studentService/StudentsInterface/loginCheckRequest", output = "http://studentService/StudentsInterface/loginCheckResponse")
    public boolean loginCheck(
        @WebParam(name = "loginCheckUsername", partName = "loginCheckUsername")
        String loginCheckUsername,
        @WebParam(name = "loginCheckPassword", partName = "loginCheckPassword")
        String loginCheckPassword);

    /**
     * 
     * @param addStudentId
     * @param addStudentAllStudents
     * @return
     *     returns studentservice.Students
     */
    @WebMethod
    @WebResult(name = "addStudentResult", partName = "addStudentResult")
    @Action(input = "http://studentService/StudentsInterface/addStudentRequest", output = "http://studentService/StudentsInterface/addStudentResponse")
    public Students addStudent(
        @WebParam(name = "addStudentId", partName = "addStudentId")
        int addStudentId,
        @WebParam(name = "addStudentAllStudents", partName = "addStudentAllStudents")
        Students addStudentAllStudents);

    /**
     * 
     * @param allStudentsDetails
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "studentDetailsResult", partName = "studentDetailsResult")
    @Action(input = "http://studentService/StudentsInterface/studentDetailsRequest", output = "http://studentService/StudentsInterface/studentDetailsResponse")
    public String studentDetails(
        @WebParam(name = "allStudentsDetails", partName = "allStudentsDetails")
        Students allStudentsDetails);

}
