
package studentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsInterface", targetNamespace = "http://studentService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsInterface {


    /**
     * 
     * @param printMarkId
     * @param printMarkMc
     * @return
     *     returns java.lang.String
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "printMarkResult", partName = "printMarkResult")
    @Action(input = "http://studentService/StudentsInterface/printMarkRequest", output = "http://studentService/StudentsInterface/printMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentService/StudentsInterface/printMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentService/StudentsInterface/printMark/Fault/IOException")
    })
    public String printMark(
        @WebParam(name = "printMarkId", partName = "printMarkId")
        int printMarkId,
        @WebParam(name = "printMarkMc", partName = "printMarkMc")
        ModuleCode printMarkMc)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param mc
     * @param insertMarkId
     * @param mark
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "insertMarkResult", partName = "insertMarkResult")
    @Action(input = "http://studentService/StudentsInterface/insertMarkRequest", output = "http://studentService/StudentsInterface/insertMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentService/StudentsInterface/insertMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentService/StudentsInterface/insertMark/Fault/IOException")
    })
    public int insertMark(
        @WebParam(name = "insertMarkId", partName = "insertMarkId")
        int insertMarkId,
        @WebParam(name = "mc", partName = "mc")
        ModuleCode mc,
        @WebParam(name = "mark", partName = "mark")
        double mark)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addStudentNewStudent
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://studentService/StudentsInterface/addStudentRequest", output = "http://studentService/StudentsInterface/addStudentResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentService/StudentsInterface/addStudent/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentService/StudentsInterface/addStudent/Fault/IOException")
    })
    public void addStudent(
        @WebParam(name = "addStudentNewStudent", partName = "addStudentNewStudent")
        Student addStudentNewStudent)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param enrollMc
     * @param enrollAnnualYear
     * @param enrollId
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "enrollResult", partName = "enrollResult")
    @Action(input = "http://studentService/StudentsInterface/enrollRequest", output = "http://studentService/StudentsInterface/enrollResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentService/StudentsInterface/enroll/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentService/StudentsInterface/enroll/Fault/IOException")
    })
    public int enroll(
        @WebParam(name = "enrollId", partName = "enrollId")
        int enrollId,
        @WebParam(name = "enrollMc", partName = "enrollMc")
        ModuleCode enrollMc,
        @WebParam(name = "enrollAnnualYear", partName = "enrollAnnualYear")
        String enrollAnnualYear)
        throws IOException_Exception, JAXBException_Exception
    ;

}
