
package studentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsInterface", targetNamespace = "http://studentService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsInterface {


    /**
     * 
     * @param addStudentNewStudent
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://studentService/StudentsInterface/addStudentRequest", output = "http://studentService/StudentsInterface/addStudentResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://studentService/StudentsInterface/addStudent/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://studentService/StudentsInterface/addStudent/Fault/IOException")
    })
    public void addStudent(
        @WebParam(name = "addStudentNewStudent", partName = "addStudentNewStudent")
        Student addStudentNewStudent)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param loginCheckPassword
     * @param loginCheckUsername
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "loginCheckResult", partName = "loginCheckResult")
    @Action(input = "http://studentService/StudentsInterface/loginCheckRequest", output = "http://studentService/StudentsInterface/loginCheckResponse")
    public boolean loginCheck(
        @WebParam(name = "loginCheckUsername", partName = "loginCheckUsername")
        String loginCheckUsername,
        @WebParam(name = "loginCheckPassword", partName = "loginCheckPassword")
        String loginCheckPassword);

}
