
package staffservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StaffsImplService", targetNamespace = "http://staffService/", wsdlLocation = "http://localhost:8080/staffService/?wsdl")
public class StaffsImplService
    extends Service
{

    private final static URL STAFFSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STAFFSIMPLSERVICE_EXCEPTION;
    private final static QName STAFFSIMPLSERVICE_QNAME = new QName("http://staffService/", "StaffsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/staffService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STAFFSIMPLSERVICE_WSDL_LOCATION = url;
        STAFFSIMPLSERVICE_EXCEPTION = e;
    }

    public StaffsImplService() {
        super(__getWsdlLocation(), STAFFSIMPLSERVICE_QNAME);
    }

    public StaffsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STAFFSIMPLSERVICE_QNAME, features);
    }

    public StaffsImplService(URL wsdlLocation) {
        super(wsdlLocation, STAFFSIMPLSERVICE_QNAME);
    }

    public StaffsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STAFFSIMPLSERVICE_QNAME, features);
    }

    public StaffsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StaffsInterface
     */
    @WebEndpoint(name = "StaffsImplPort")
    public StaffsInterface getStaffsImplPort() {
        return super.getPort(new QName("http://staffService/", "StaffsImplPort"), StaffsInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StaffsInterface
     */
    @WebEndpoint(name = "StaffsImplPort")
    public StaffsInterface getStaffsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://staffService/", "StaffsImplPort"), StaffsInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STAFFSIMPLSERVICE_EXCEPTION!= null) {
            throw STAFFSIMPLSERVICE_EXCEPTION;
        }
        return STAFFSIMPLSERVICE_WSDL_LOCATION;
    }

}
