
package staffservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffsInterface", targetNamespace = "http://staffService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StaffsInterface {


    /**
     * 
     * @param loginCheckPassword
     * @param loginCheckUsername
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "loginCheckResult", partName = "loginCheckResult")
    @Action(input = "http://staffService/StaffsInterface/loginCheckRequest", output = "http://staffService/StaffsInterface/loginCheckResponse")
    public boolean loginCheck(
        @WebParam(name = "loginCheckUsername", partName = "loginCheckUsername")
        String loginCheckUsername,
        @WebParam(name = "loginCheckPassword", partName = "loginCheckPassword")
        String loginCheckPassword);

}
