
package staffservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffsInterface", targetNamespace = "http://staffService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffsInterface {


    /**
     * 
     * @param addStaffNewStaff
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @Action(input = "http://staffService/StaffsInterface/addStaffRequest", output = "http://staffService/StaffsInterface/addStaffResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://staffService/StaffsInterface/addStaff/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://staffService/StaffsInterface/addStaff/Fault/IOException")
    })
    public void addStaff(
        @WebParam(name = "addStaffNewStaff", partName = "addStaffNewStaff")
        AcademicStaffMember addStaffNewStaff)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @return
     *     returns staffservice.ArrayList
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://staffService/StaffsInterface/getStaffRequest", output = "http://staffService/StaffsInterface/getStaffResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://staffService/StaffsInterface/getStaff/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://staffService/StaffsInterface/getStaff/Fault/IOException")
    })
    public ArrayList getStaff()
        throws IOException_Exception, JAXBException_Exception
    ;

}
